export type Vacancy = {
  id: string;
  title: string;
  employer: string | null;
  country: string | null;
  category: string | null;
  positions: number | null;
  salary: string | null;
  currency: string | null;
  accommodation: string | null;
  food: string | null;
  transportation: string | null;
  duration: string | null;
  experience: string | null;
  qualification: string | null;
  age: string | null;
  gender: string | null;
  deadline: string | null;
  description: string | null;
  requirements: string | null;
  benefits: string | null;
  status: "published" | "unpublished";
  featured: boolean;
  urgent: boolean;
  created_at: string;
  updated_at: string;
};

export type Application = {
  id: string;
  reference: string;
  full_name: string;
  father_name: string | null;
  dob: string | null;
  cnic: string | null;
  gender: string | null;
  marital_status: string | null;
  nationality: string | null;
  city: string | null;
  province: string | null;
  mobile: string;
  whatsapp: string | null;
  email: string | null;
  profession: string;
  job_category: string | null;
  qualification: string | null;
  total_experience: string | null;
  overseas_experience: string | null;
  current_employer: string | null;
  current_job_title: string | null;
  preferred_country: string | null;
  preferred_job: string | null;
  expected_salary: string | null;
  vacancy_id: string | null;
  cv_path: string | null;
  passport_path: string | null;
  cnic_file_path: string | null;
  photo_path: string | null;
  other_docs_paths: string[] | null;
  status: "New" | "Under Review" | "Shortlisted" | "Interview" | "Selected" | "Rejected";
  admin_notes: string | null;
  created_at: string;
  updated_at: string;
};

export type EmployerInquiry = {
  id: string;
  company_name: string;
  contact_person: string;
  email: string;
  phone: string;
  country: string | null;
  profession: string | null;
  workers: number | null;
  qualification: string | null;
  experience: string | null;
  salary: string | null;
  benefits: string | null;
  notes: string | null;
  status: "New" | "Contacted" | "In Progress" | "Closed";
  admin_notes: string | null;
  created_at: string;
  updated_at: string;
};

export type Country = { id: string; name: string; sort_order: number };
export type JobCategory = { id: string; name: string; sort_order: number };
